unique_ids:
  assets:
    standard-page.html: AUXFOX26GB42HE6TKU3CW3IGW4CQRX5J
    theme.css: VJBICR76HR2ITZGNUDFAJAXRUZAPC7RK
  forms:
    Form1: POPRN7UTUNW57EETUWPIAYPOYAWWZ6ZL
  modules: {}
  scripts: {}
  server_modules: {}
